export const rarity = ["Common", "Bronze", "Silver", "Gold", "Diamond"]

export const series = [
    "2022 All-Star",
    "2022 Finest",
    "2022 Postseason",
    "2nd Half Heroes",
    "All-Star",
    "Awards",
    "Breakout",
    "Cover Athletes",
    "Faces of the Franchise",
    "Finest",
    "Future Stars",
    "Home Run Derby",
    "Live",
    "Milestone",
    "Monthly Awards",
    "Postseason",
    "Prime",
    "Prospect",
    "Rookie",
    "Signature",
    "Takashi Okazaki",
    "Topps Now",
    "Veteran",
]

export const teams = [
  "Angels",
  "Astros",
  "Athletics",
  "Blue Jays",
  "Braves",
  "Brewers",
  "Cardinals",
  "Cubs",
  "Diamondbacks",
  "Dodgers",
  "Giants",
  "Guardians",
  "Mariners",
  "Marlins",
  "Mets",
  "Nationals",
  "Orioles",
  "Padres",
  "Pirates",
  "Phillies",
  "Rangers",
  "Rays",
  "Reds",
  "Red Sox",
  "Rockies",
  "Royals",
  "Tigers",
  "Twins",
  "White Sox",
  "Yankees",
  "Free Agents"
]

export const quirks = [
  "20 Vision",
  "Bomber",
  "Breaking Ball Hitter",
  "Buntmaster",
  "Cannon",
  "Catcher Pop Time",
  "Cheesy",
  "Control Artist",
  "Day Player",
  "Dead Red",
  "Fighter",
  "First-Pitch Hitter",
  "Grounded",
  "Hitting Machine",
  "Homebody",
  "Illusionist",
  "Knee Buckler",
  "Knuckleballer",
  "Mr. Splitee",
  "Night Player",
  "Outlier I",
  "Outlier II",
  "Pickoff Artist",
  "Pinch Hitter",
  "Platoon",
  "Pressure Cooker",
  "Quick Reflexes",
  "Rally Monkey",
  "Road Warrior",
  "Sinkerballer",
  "Situational Hitter",
  "Sniper",
  "Softhands",
  "Speedster",
  "Stingy",
  "Stopper",
  "Thief",
  "Unbreakable",
  "Unfazed",
  "Untouchable",
  "Vacuum",
  "Walker",
  "Workhorse",
]

export const locations = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "Aruba",
  "Australia",
  "Bahamas",
  "Brazil",
  "California",
  "Canada",
  "China",
  "Colombia",
  "Colorado",
  "Connecticut",
  "Cuba",
  "Curacao",
  "Czech Republic",
  "Delaware",
  "Dominican Republic",
  "Florida",
  "Georgia",
  "Germany",
  "Great Britain",
  "Guam",
  "Hawaii",
  "Honduras",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Japan",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maryland",
  "Massachusetts",
  "Mexico",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Netherlands",
  "Nevada",
  "New Jersey",
  "New Mexico",
  "New York",
  "Nicaragua",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Panama",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "South Korea",
  "Taiwan",
  "Tennessee",
  "Texas",
  "Utah",
  "Venezuela",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "Washington, DC",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
]
